spring:
  datasource:
    url: jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      network-tier: internal
      exposed: "false"

order:
  max-quantity-per-order: 10
  default-status: PENDING

resilience:
  circuit-breaker:
    failure-threshold: 3
    timeout-duration: 5s
    wait-duration-open: 15s
    sliding-window-size: 5
    failure-rate-threshold: 50
  retry:
    max-attempts: 3
    initial-backoff: 500ms
    multiplier: 2

logging:
  level:
    ie.tus.jeff.order: DEBUG
    io.github.resilience4j: DEBUG
  pattern:
    console: "%d{ISO8601} [%thread] %-5level %logger{36} - [%X{traceId}] - %msg%n"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans